### ISSUE TITLE
Pixel 7 Pro / Neighbor Cells Always Tagged [SCC]

### ISSUE THREAD

**Issue by cybershieldms** [bluelinepc/signalcheck#29]
**Describe the bug**
The neighbor cells on the Pixel 7 Pro (Tenor 2 SoC) are all tagged [SCC] 

**To Reproduce**
Always shows

**Expected behavior**
If this means small cell, this is incorrect.  I've noticed the Pixel 6 (Tenor 1) and 7 (Tenor 2) cannot identify small cells on AT&T compared to the Samsung Galaxy Z Flip 4 (Snapdragon 8+ Gen 1)

**Screenshots**
![Screenshot_20221031-164411](https://user-images.githubusercontent.com/1704918/199117267-125da227-1096-48a3-9555-4694aef27edd.png)

**Device details**
 - Device:  Pixel 7 Pro (US Unlocked - GA03455-US)
 - Android version: 13 (TD1A.220804.031 - October 2022)
 - SignalCheck version:  4.71

**Additional context**
Please add any other context about the problem here.

**Comment by cybershieldms** [comment]
Uploaded diagnostics from app.

**Comment by mikejeep** [comment]
SCC stands for Secondary Component Carrier; it refers to cells available for carrier aggregation that are not the primary active connection (aka "neighbor cells"). Code was added to help identify these secondary cells vs. Primary Component Carrier (PCC) cells as part of the ongoing rollout of dual SIM support. These tags were not visible previously because the API methods were apparently not fully implemented until Android 13. Now that the OS is properly recognizing these methods, I am evaluating how to utilize them in future releases.
