### ISSUE TITLE
Incorrect band for 5G NR (NSA)

### ISSUE THREAD

**Issue by Ahmad-Amsyar** [bluelinepc/signalcheck#56]
**Describe the bug**
The band for 5G NR show as n77 when in Malaysia, we only use n78 as 5G band and B28 as anchor band.

**To Reproduce**
1) Enable 5G. 
2) Open SignalCheck app. 
3) 4G anchor band shown correctly but 5G band is wrong.

**Expected behavior**
4G anchor band shown as B28 and 5G is shown as N78.

**Screenshots**
![Screenshot_2024-02-26-09-59-22-062_com.blueline.signalcheck-edit.jpg](https://github.com/bluelinepc/signalcheck/assets/27284123/6f818ede-3ce7-4c8e-9465-bbffe3e45c57)

**Device details**
 - Device: POCO X4 GT (MIUI 14.0.7)
 - Android version: Android 13
 - SignalCheck version: 4.83

**Additional context**
Malaysia is using single wholesale network (Digital Nasional) for 5G. Which means all telco in Malaysia use the same band for 5G NSA.

Other app such as NetMonster and G-Nettrack doesn't seems to have this problem.

![Screenshot_2024-02-26-10-00-51-460_com.microsoft.emmx-edit.jpg](https://github.com/bluelinepc/signalcheck/assets/27284123/0a9a955f-ea51-4090-8c97-7c6a66c69d58)
https://en.wikipedia.org/wiki/Digital_Nasional

**Comment by mikejeep** [comment]
Thank you for this report. Unfortunately there are many issues with the native Android methods to identify 5G-NR bands. In cases where a particular frequency is part of multiple bands (n77 and n78 in your case), the OS reports the lowest one. I will implement a workaround in the next app update.

**Comment by mikejeep** [comment]
If you experience further problems after the next app update is released, please feel free to re-open this issue.

**Comment by eladts** [comment]
This issue is still not resolved. When my Pixel 8 is taking on T-Nobile CZ (home network is Google Fi/T-Mobile US), n1 is misidentified as n66 and n78 is misidentified as n77.

<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/0a6aeb22-a6a8-469f-af9e-59142e30f3d0" />

<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/a6a64603-69fd-4418-b006-371ba0213e54" />

@mikejeep Please reopen this issue.
