### ISSUE TITLE
Connection Speed And connection speed interval

### ISSUE THREAD

**Issue by inth3shadows** [bluelinepc/signalcheck#60]
**Describe the solution/feature you'd like**
Connection Speed & Connection speed update interval
Connection speed update interval would be in settings for the user to choose how often they want to update connection speed 
( I see speed is on wifi - but not LTE. Perhaps there is a reason & it isn't possible. )

**Describe alternatives you've considered**
Only alternatives I am aware of are other applications 

**Additional context**
Looking to get speed and connection data in one place

**Comment by mikejeep** [comment]
Thank you for the suggestion. WiFi speed is displayed because the operating system reports it; SignalCheck simply displays that value. There is no comparable value for mobile connections. In order to get a "connection speed" for mobile connections, a speed test would need to be run, which would consist of uploading and downloading data to a remote server. Unfortunately this is well beyond the scope of this app and not something I will be able to add. Ookla Speedtest and other similar apps do a good job of reporting speed test results.
